### ISSUE TITLE
Issue building 

### ISSUE THREAD

**Issue by wiless** [gonum/internal#55]
I have been using the gonum/plot package till today. I did a pull of the recent plotter package, as well as the gonum/internal package. I get the following error, seems source code moved from the asm folder to subfolders ?? Am I missing something ?
```
package github.com/gonum/internal/asm: no buildable Go source files in $GOAPTH/src/github.com/gonum/internal/asm 
```

Please help/suggest

**Comment by wiless** [comment]
Deleting all repos under github.com/gonum and a fresh go get -d fixed it

**Comment by kortschak** [comment]
You should be able to just `go get -u github.com/gonum/plot/...` to get the same effect.
